#!/bin/bash

overlay=/usr/share/pixmaps/lockoverlay.png

notify-send "Locking screen..."
scrot -o /tmp/currentworkspace.png
convert /tmp/currentworkspace.png -brightness-contrast -40x-10 -blur 0x20 /tmp/currentworkspaceblur.png
composite -gravity southeast $overlay /tmp/currentworkspaceblur.png /tmp/lockbackground.png
i3lock -i /tmp/lockbackground.png
